#Lottery System Configuration
#Fri Dec 19 17:05:20 CST 2025
database.username=root
ticket.price=2.0
prize.first=500000
admin.password=admin123
database.password=root
prize.special=5000000
database.url=jdbc\:mysql\://localhost\:3306/lottery_db?useSSL\=false&serverTimezone\=UTC
max.bet.count=10
admin.username=admin
user.init.balance=100.0
